"""initial schema

Revision ID: bd37c658741a
Revises: 
Create Date: 2026-08-26 05:55:15.709542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd37c658741a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Enum('agent', 'human', 'system', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('evolution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_date', sa.Date(), nullable=False),
    sa.Column('variations_tested', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=255), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.Column('demo_validated', sa.Boolean(), nullable=False),
    sa.Column('human_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evolution_logs'))
    )
    with op.batch_alter_table('evolution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolution_logs_cycle_date'), ['cycle_date'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('backtest_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_model_versions_version'))
    )
    op.create_table('q_values',
    sa.Column('state_key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('q_value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state_key', 'action', name=op.f('pk_q_values'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('approval', 'crisis', 'info', name='alerttype', native_enum=False, length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response', sa.Enum('yes', 'no', 'timeout', name='alertresponse', native_enum=False, length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'elite', name='plan', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'canceled', 'incomplete', name='subscriptionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('stripe_id', sa.String(length=64), nullable=True),
    sa.Column('renews_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('stripe_id', name=op.f('uq_subscriptions_stripe_id'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('deriv_token_encrypted', sa.Text(), nullable=True),
    sa.Column('broker_type', sa.String(length=32), nullable=False),
    sa.Column('account_login', sa.String(length=64), nullable=True),
    sa.Column('account_type', sa.Enum('demo', 'live', name='accounttype', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_api_credentials_account_id_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_credentials_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_credentials'))
    )
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_credentials_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('allocated_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('active_markets', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('risk_phase', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('demo_lock_until', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('risk_phase >= 0 AND risk_phase <= 5', name=op.f('ck_configurations_risk_phase_range')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_configurations_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations'))
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configurations_account_id'), ['account_id'], unique=True)

    op.create_table('equity_snapshots',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_equity_snapshots_account_id_accounts')),
    sa.PrimaryKeyConstraint('account_id', 'timestamp', name=op.f('pk_equity_snapshots'))
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('apex_layer_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('decision', sa.Enum('BUY', 'SELL', 'WAIT', name='signaldecision', native_enum=False, length=32), nullable=False),
    sa.Column('reason_text', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_signals_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_timestamp'), ['timestamp'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('buy', 'sell', name='tradedirection', native_enum=False, length=32), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sl_initial', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sl_current', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tp', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('lots', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('open', 'be', 'trailing', 'closed', name='tradestatus', native_enum=False, length=32), nullable=False),
    sa.Column('score_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('filters_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_trades_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_account_id_opened_at', ['account_id', 'opened_at'], unique=False)

    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('hmm_state', sa.String(length=32), nullable=True),
    sa.Column('session', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_patterns_trade_id_trades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patterns'))
    )
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patterns_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patterns_trade_id'))

    op.drop_table('patterns')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_account_id_opened_at')

    op.drop_table('trades')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_timestamp'))
        batch_op.drop_index(batch_op.f('ix_signals_account_id'))

    op.drop_table('signals')
    op.drop_table('equity_snapshots')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_account_id'))

    op.drop_table('configurations')
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_credentials_account_id'))

    op.drop_table('api_credentials')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('q_values')
    op.drop_table('model_versions')
    with op.batch_alter_table('evolution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolution_logs_cycle_date'))

    op.drop_table('evolution_logs')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
